---
# This playbook creates an entire endpoint.

- name: perform common configuration on all endpoints
  hosts: endpoints
  become: yes
  roles:
    - endpoint

- name: perform mois specific configuration
  hosts: mois
  become: yes
  roles:
    - mois

- name: perform oscar specific configuration
  hosts: oscar
  become: yes
  roles:
    - oscar
