---
- name: restart fail2ban
  service: name=fail2ban state=restarted

- name: restart firewall
  ufw: state=reloaded

- name: restart ssh
  service: name=ssh state=restarted

- name: restart sysstat
  service: name=sysstat state=restarted
