---
####################################################################################################
# These tasks ensure that the reverse tunnel from the endpoint to the anchor server exists.
#
# Since the endpoint will sit behind a firewall we will not be able to connect to it directly.
# The reverse tunnel will allow us to connect to the endpoint via the anchor server.
####################################################################################################

- name: Ensure autossh package is present
  apt:
    name: autossh
    state: present

- name: Configure /home/hdc/.ssh/config to not hash known hosts
  template:
    src: home/hdc/.ssh/config.j2
    dest: /home/hdc/.ssh/config
    owner: hdc
    group: hdc
    mode: 0644
  notify: restart autossh

- name: Configure /home/hdc/.ssh/known_hosts to include anchor
  template:
    src: home/hdc/.ssh/known_hosts.j2
    dest: /home/hdc/.ssh/known_hosts
    owner: hdc
    group: hdc
    mode: 0644
  notify: restart autossh

- name: Configure /etc/systemd/system/autossh.service
  template:
    src: etc/systemd/system/autossh.service.j2
    dest: /etc/systemd/system/autossh.service
    owner: root
    group: root
    mode: 0644
  notify: restart autossh

- name: Enable the autossh service
  systemd:
    daemon_reload: true
    name: autossh
    state: started
    enabled: true
  notify: restart autossh
