---
# These tasks ensure that fail2ban is installed and configured to:
# - Permanently ban if 10 failures in 10 minutes

- name: Ensure fail2ban package is present
  apt: name=fail2ban state=present

- name: Configure /etc/fail2ban/jail.local
  template: src=etc/fail2ban/jail.local.j2 dest=/etc/fail2ban/jail.local owner=root group=root mode=0644
  notify: restart fail2ban
