---
###################################################################################################
# These tasks ensure that the ufw package is installed and configured.
#
# UFW is an uncomplicated firewall that we are using as our first line of defense against
# malicious users. The firewall is configured by default to deny all incoming and routed
# packets while allowing all outgoing packets. Exceptions are provided to allow SSH connections
# from an anchor server.
###################################################################################################

- fail: msg="Variable ssh_anchor_ip is required"
  when: ssh_anchor_ip is undefined

- name: Ensure ufw package is installed
  apt:
    name: ufw
    state: present

- name: Configure /etc/default/ufw
  template:
    src: etc/default/ufw.j2
    dest: /etc/default/ufw
    owner: root
    group: root
    mode: 0644
  notify: restart firewall

- name: Set logging level to low
  ufw:
    logging: low
  notify: restart firewall

- name: Set default to allow all outgoing traffic
  ufw:
    direction: outgoing
    policy: allow
  notify: restart firewall

- name: Set default to deny all incoming traffic
  ufw:
    direction: incoming
    policy: deny
  notify: restart firewall

- name: Set default to deny all routed traffic
  ufw:
    direction: routed
    policy: deny
  notify: restart firewall

- name: Allow SSH from anchor server
  ufw:
    port: 22
    rule: allow
    proto: tcp
    from_ip: {{ ssh_anchor_ip }}
  notify: restart firewall

- name: Ensure ufw is enabled
  ufw:
    state: enabled
  notify: restart firewall
