---
# These tasks ensure that monit is installed and configured to:

- fail: msg="Variable mmonit_url is required"
  when: mmonit_url is undefined

- name: Ensure monit package is present
  apt: name=monit state=present

- name: Configure /etc/monit/monitrc
  template: src=etc/monit/monitrc.j2 dest=/etc/monit/monitrc owner=root group=root mode=0600
  notify: restart monit

- name: Configure /etc/monit/conf-enabled/base
  template: src=etc/monit/conf-enabled/base.j2 dest=/etc/monit/conf-enabled/base owner=root group=root mode=0644
  notify: restart monit
