---
###################################################################################################
# These tasks ensure that the network is configured.
#
# There are two interfaces created.
# eno1   A DHCP interface that will be used for all outbound traffic.
# eno1:0 A static interface that will be used by the adapter to connect to the endpoint.
###################################################################################################

- name: Configure generic /etc/network/interfaces
  template:
    src: etc/network/interfaces.gen.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  notify: restart network
  


- name: Copy clinic specific interface configuration file
  tags:
    - clinic
  template:
    src: etc/network/interfaces.d/eno10.cfg.j2
    dest: /etc/network/interfaces.d/eno1:0.cfg
    owner: root
    group: root
    mode: 0644 
 
- name: Append eno1:0 config file in /etc/network/interfaces
  tags:
    - clinic
  lineinfile:
    path: /etc/network/interfaces
    line: "source /etc/network/interfaces.d/*.cfg"
    insertafter: EOF
    backup: yes
    owner: root
    group: root
    mode: 0644
  notify: restart network 


