---
###################################################################################################
# These tasks ensure that common packages are present on the server.
#
# Currently these packages include nano (basic text editor) and git (version control).
###################################################################################################

- name: Ensure common packages are present
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nano
    - git
