---
# These tasks ensure the postgres package is installed and configured to:

- fail: msg="Variable crypt_dir is required"
  when: crypt_dir is undefined

- name: Ensure postgres package is present
  apt: name=postgresql state=present

- name: Configure /etc/postgresql/9.5/main/postgresql.conf
  template: src=etc/postgresql/9.5/main/postgresql.conf.j2 dest=/etc/postgresql/9.5/main/postgresql.conf owner=postgres group=postgres mode=0644
  notify: restart postgresql

- name: Configure /etc/postgresql/9.5/main/pg_hba.conf
  template: src=etc/postgresql/9.5/main/pg_hba.conf.j2 dest=/etc/postgresql/9.5/main/pg_hba.conf owner=postgres group=postgres mode=0640
  notify: restart postgresql
