---
###################################################################################################
# These tasks ensure that the unattended-upgrades package is installed and configured
#
# The unattended-upgrades package is used to automatically update the packages on the endpoint.
# We have configured it to:
# - Only upgrade security packages.
# - Scheduled daily to to update the package list, download, and install the available upgrades.
# - Scheduled weekly to auto clean the local cache.
###################################################################################################

- name: Ensure unattended-upgrades package is present
  apt:
    name: unattended-upgrades
    state: present

- name: Configure /etc/apt/apt.conf.d/20auto-upgrades
  template:
    src: etc/apt/apt.conf.d/20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

- name: Configure /etc/apt/apt.conf.d/50unattended-upgrades
  template:
    src: etc/apt/apt.conf.d/50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644


- name: Configure /etc/systemd/system/apt-daily.timer.d/override.conf
  template:
    src: etc/systemd/system/apt-daily.timer.d/override.conf.j2
    dest: /etc/systemd/system/apt-daily.timer.d/override.conf
    owner: root
    group: root
    mode: 0644
